exclude: docs
repos:
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.6.0
    hooks:
      - id: reorder-python-imports
        language_version: python3
        args: [--py3-plus]
        exclude: ^dynaconf/vendor*
  - repo: https://github.com/ambv/black
    rev: 21.7b0
    hooks:
      - id: black
        args: [--line-length=79]
        language_version: python3
        exclude: ^dynaconf/vendor*
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
        language_version: python3
        exclude: ^dynaconf/vendor*
      - id: end-of-file-fixer
        language_version: python3
        exclude: ^dynaconf/vendor*
      - id: check-yaml
        language_version: python3
        exclude: ^dynaconf/vendor*
      - id: check-merge-conflict
        language_version: python3
        exclude: ^dynaconf/vendor*
      - id: debug-statements
        language_version: python3
        exclude: ^dynaconf/vendor*
      - id: fix-encoding-pragma
        language_version: python3
        exclude: ^dynaconf/vendor*
        args: [--remove]
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        args: ['--ignore=F403,W504,W503,F841,E401,F401,E402']
        language_version: python3
        exclude: ^dynaconf/vendor*
